### ISSUE TITLE
Upgrading to Meteor 1.2 causes an error in table views

### ISSUE THREAD

**Issue by CaptainN** [sachinbhutani/flow-db-admin#3]
On the list pages, the table based list views get broken when upgrading to Meteor 1.2.

**Comment by edsadr** [comment]
experimenting the same issue

**Comment by sachinbhutani** [comment]
Please update to version 1.1

**Comment by CaptainN** [comment]
It looks like my change was reverted in a following commit:
https://github.com/sachinbhutani/flow-db-admin/commit/417b3a92dadd36e60996ed89daa9cd46e2ff2438

**Comment by CaptainN** [comment]
or actually removed, then reverted.

**Comment by CaptainN** [comment]
I can confirm the table views are fixed. Thanks!

**Comment by thomasspiesser** [comment]
hey, could someone point me in the direction on what was broken and how it got fixed? coz some issue occurs in the original yobiben:admin package..thanks!

**Comment by CaptainN** [comment]
The fix is somewhere in the m1.2 commits from Sep 26, 2015. I briefly took a look, but much was changed in there, and in the little amount of time I had to look at it, I wasn't able to find the specific change that fixed it.

**Comment by sachinbhutani** [comment]
The problem was specifically with edit and delete button on each document in the tabular list, but there are lot of other difference between how yogiben:admin and flow-db-admin work due to use of flow-router and document id based URLs
Main cause was change in context for the templates, not sure what part of Meteor 1.2 caused it, but it changed the way this was used in a few templates

**Comment by thomasspiesser** [comment]
i skimmed the commit briefly but a lot has changed indeed. thanx though, i will keep an eye out for change of data context in the templates.
